version: 0.2
phases:
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "Build"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Post build"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
      
